# Change these first
owner: MacKisco # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: "Le Petit Atelier Luthi"
    url: https://lepetitatelierluthi.fr
  - name: "L'Eire de rien"
    url: https://leirederien.fr
  - name: "Aviva-stats"
    url: https://aviva-stats.netlify.app

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "MacKisco's Upptime"
  introTitle: "Websites monitoring with Upptime"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
